### ISSUE TITLE
TypeError: Cannot handle this data type

### ISSUE THREAD

**Issue by yhgon** [Yangyangii/DeepConvolutionalTTS-pytorch#1]
I'm wondering which version of  plot library do I need. 

When I try to train error  for `CxHxW  vs HxWxC. ` occurs during save plot file  
https://github.com/Yangyangii/DeepConvolutionalTTS-pytorch/blob/master/train.py#L75

 I'm using `tensorboardX 1.1` , `Pillow   6.0.0` and `Matplotlib 2.1.0`
Could you provide which TensorboardX and PIL library do you use?

```
Traceback (most recent call last):                                    
  File "/opt/conda/lib/python3.6/site-packages/PIL/Image.py", line 2533, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 202), '|u1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 212, in <module>
    main(network=network)
  File "train.py", line 196, in main
    batch_size=args.batch_size, ckpt_dir=ckpt_dir, writer=writer)
  File "train.py", line 75, in train
    writer.add_image('train/alignments', att2img(alignment), global_step) # (Tx, Ty)
  File "/opt/conda/lib/python3.6/site-packages/tensorboardX/writer.py", line 338, in add_image
    self.file_writer.add_summary(image(tag, img_tensor), global_step)
  File "/opt/conda/lib/python3.6/site-packages/tensorboardX/summary.py", line 158, in image
    image = make_image(tensor)
  File "/opt/conda/lib/python3.6/site-packages/tensorboardX/summary.py", line 166, in make_image
    image = Image.fromarray(tensor)
  File "/opt/conda/lib/python3.6/site-packages/PIL/Image.py", line 2535, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type

```

**Comment by yhgon** [comment]
TensorboardX==1.6 support grayscale and it works well.
